### ISSUE TITLE
Bad rendering on Android 2.3’s default browser

### ISSUE THREAD

**Issue by linkmauve** [citra-emu/citra-emu.github.io#24]
A friend gave me a screenshot of the rendering of the website, and that it is completely unusable currently:
![Android 2.3 rendering of the main page](https://dl.dropboxusercontent.com/u/52886258/citra.png)

**Comment by archshift** [comment]
Unfortunately, you can tell from the screenshot that your friend's (third-party) browser does not support *many* HTML5/CSS3 features. The two big ones are SVG support and viewport units. These things have been supported even in *Internet Explorer* for six years already.

**Comment by linkmauve** [comment]
It apparently uses the same rendering engine as the default browser, and thus doesn’t render any better there.

**Comment by isaacrg** [comment]
@archshift An immediate concern might be the lack of a meta viewport value. I have proposed a fix to this in #25.

**Comment by linkmauve** [comment]
Android 2.3 isn’t really used anymore, closing.
